### ISSUE TITLE
Cool setup!

### ISSUE THREAD

**Issue by labsforge** [trungk18/jira-clone-angular#68]
Hi just to let u know I was thinking doing the same setup, I think works really well :)

About the guard for fetching into the store, maybe you could use a resolver instead 🤔

**Comment by trungk18** [comment]
Thank for stopping by!!!
Guard/resolver would both work actually, but since the API was very simple and has no permission based. The guard that I wrote was not actually being used. I will release it together on phase two with actual API.

**Comment by evolmk** [comment]
I agree with "cool setup", UI came out very clean using `ng-zorro-antd` components.

Do you plan on using RxJS, and subscribing to your API's http requests?

Keep up the good work, i'll check back once you develop your backend and angular services to add/update your components, i use express personally but Nest is similar.

**Comment by trungk18** [comment]
@evolmk To answer your questions
1. Yeah for sure, I am working on the API request. All of them will be GraphQL with Apollo so that It might not looks very similar to the REST API. You can take a look at the wokr-in-progress auth service with the actual API there.

https://github.com/trungk18/jira-clone-angular/blob/feature/gql/frontend/src/app/core/auth/auth.service.ts

2. jira-clone is my first project using Akita and I have never use it on any of my work application but personally, I like the way it works.

The second project I used Akita is the recent Tetris game, not sure if you can call it production ready app but people have already started using it in the last one week 😂 You can take a look https://tetris.trungk18.com/

Akita abstracts a lot of process for you comparing to the purely using RxJS and BehaviourSubjects. Think about BehaviorSubjects is a simple version of Akita, it could function pretty well by itself but you need to write more code. That's it. Akita came out with some concept and util method to speed up that process for you. 

The backend might come in sometimes in August, that's my current target. If you want to get more update about that, you can follow me on Twitter. I usually post the update on that.
