### ISSUE TITLE
ng serve is not working

### ISSUE THREAD

**Issue by swapnilsworld** [trungk18/jira-clone-angular#88]
**Describe the bug**
ng serve is not working when followed the steps in part 1 of your tutorial. :(
I am getting the below error msg.

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(customWebpackConfig).

Failed to setup the tailwind/webpack configuration.... hell its damn confusing whats wrong in it.

**Expected behavior**
server should start wthout error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win 10]
- Angular 11
**Smartphone (please complete the following information):**

**Additional context**

**Comment by trungk18** [comment]
Thanks @swapnilsworld for reporting. I will look into it and get back to you.

**Comment by trungk18** [comment]
@swapnilsworld Appreciate if you can provide me the source code. I am not sure at which stage you are facing the error.

**Comment by trungk18** [comment]
Hey @swapnilsworld,

I can reproduce it now. Seems there are several issues that I am not able to fix all of them. I updated to mention about them on this blog post.

https://trungk18.com/experience/configure-tailwind-css-with-angular/

For now, I recommended to use [ngneat/tailwind](https://github.com/ngneat/tailwind) for TailwindCSS configuration. You could find it in the same link above.

Thanks for reporting the issue. Sorry for the late reply since I am also busy with other work 😂
